Add pairing logic and ts-node
sandboxnu/boba-buddies pull request #8
Opened 2021-10-20 15:09 UTC by VKong6019

hey buddies,

I saw jia start the slack bot dms 👀, so I thought I just make this into a pr to expedite the process. 

The way the pairing works in `generatePair.ts` is that it'll partition an array of users in a channel by 2s. If there's an uneven number of people, then add that loner into some existing pair. 

Idk if this is added in my commits, but I installed `ts-node`  and used that to run typescript files easily.
so then I just do `ts-node pairAndIntroduce.ts`
https://www.npmjs.com/package/ts-node

2021-10-20 15:15 UTC, VKong6019 commented on utils/generatePairs.ts
>  const TESTING_CHANNEL_ID = "C02J6R0SUSX";
note: will need to change this later

2021-10-20 17:31 UTC, ryandrew14 requested changes
looks great tysm but it's actually good practice to commit package-lock.json, see here: https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5

also any chance u could write tests for this one 😄 lol it would be a nice easy thing to set up Jest with and since ur the test wizard of the team

2021-10-20 17:31 UTC, ryandrew14 commented on utils/generatePairs.ts
> +        const lonelyMember: string[] = pairs.pop() ?? [];
this thing so useful i swear its like every 3 lines I write

2021-10-20 17:31 UTC, ryandrew14 commented on utils/generatePairs.ts
>  const TESTING_CHANNEL_ID = "C02J6R0SUSX";
could u write todo comment

2021-10-21 05:49 UTC, ryandrew14 commented on __tests__/generatePairs.test.ts
> +    it('should pair a list with 1 member', async () => {
typo

2021-10-22 02:00 UTC, ryandrew14 approved these changes
🤠 yeehaw

2021-10-22 03:01 UTC, merged